### ISSUE TITLE
Admin : I can import my catalog from Postico

### ISSUE THREAD

**Issue by FabienLebas** [FabienLebas/srt_react#6]

**Comment by dominique-bureau** [comment]
l'informatique alimente un catalogue local directement dans POSTICO. Dans le cadre du projet il n'y aura pas d'appels API vers un catalogue externe. 

Ce catalogue doit être déclaré appartenir à une réservoir (le catalogue du magasin chilien peut être différemment du catalogue du magasin colombien)
